#!/bin/bash
#Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"
source ~/.profile 
source ~/.scripts/env.sh
xrandr --output LVDS-1 --off
setxkbmap br
# Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND="#1a2128"
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

## Configurations -------------------------------#
bspc config border_width 1
bspc config window_gap  10
bspc config split_ratio 1


bspc config focused_border_color "#ef8891" 
bspc config normal_border_color "#131a21"
bspc config active_border_color "#1a2128"
bspc config presel_feedback_color "#131a21"

# bspc config borderless_monocle true
# bspc config gapless_monocle true
# bspc config paddingless_monocle false
# bspc config single_monocle false
# bspc config focus_follows_pointer true


## Window rules -------------------------------#

# remove all rules first

# 1 > terminal
# 
# # 4 > office
# declare -a office=(Geany Gucharmap Evince \
# libreoffice-writer libreoffice-calc libreoffice-impress \
# libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
# for i in ${office[@]}; do
   # bspc rule -a $i desktop='^4' follow=on focus=on; done
# 
# # 5 > media
# declare -a media=(Audacity mpv mplayer lxmusic Gimp Gimp-2.8)
# for i in ${media[@]}; do
   # bspc rule -a $i desktop='^5' follow=on focus=on; done
# 
# # 6 > settings
# bspc rule -a GParted desktop='^6' follow=on focus=on
# declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
# System-config-printer.py Pavucontrol Exo-helper-1)
# for i in ${settings[@]}; do
   # bspc rule -a $i desktop='^6' state=floating follow=on focus=on; done
# 
# # special rules
# bspc rule -a alacritty-float state=floating follow=on focus=on
# bspc rule -a Pcmanfm state=floating follow=on focus=on
# bspc rule -a Onboard state=floating follow=on focus=on
# bspc rule -a Audacious state=floating follow=on focus=on
# bspc rule -a Firefox:Places state=floating follow=on focus=on
# bspc rule -a Viewnior state=floating follow=on focus=on
# bspc rule -a Nm-connection-editor state=floating follow=on focus=on
# bspc rule -a Conky state=floating manage=off
# bspc rule -a stalonetray state=floating manage=off

## Autostart -------------------------------#

# Kill if already running
killall -9 sxhkd xsettingsd dunst xfce4-power-manager

# Lauch notification daemon

#
# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
#xsetroot -cursor_name left_ptr

# Restore wallpaper
bash $HOME/.fehbg
loop() {
	notify-send bspwm 'loop started.'
	while true
	do 
	dunst \
	-geom "280x50-10+38" -frame_width "1" -font "Iosevka Custom 9" \
	-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
	-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
	-cb "$BACKGROUND" -cf "$RED" -cfr "$RED"
	sleep 5
	done
}
loop &

# Start mpd
exec mpd &
#bspbar
bspcolors
#bspcomp
bspfloat &
bspc monitor -d $(seq 5)
bash ~/.config/polybar/launch.sh --blocks 
a() {
	sleep 2
	bash ~/.config/polybar/launch.sh --blocks 
}
a &
notify-send bspwm ready.
