local saga = require('lspsaga')
local vimp = require('vimp') 
vimp.nnoremap('<C-a>', function()
	require('lspsaga.codeaction').code_action()
end)
vimp.nnoremap('<C-k>', function() 
  	require('lspsaga.signaturehelp').signature_help()
end)
vimp.nnoremap('<C-r>', function() 
	require('lspsaga.rename').rename()
end)
saga.init_lsp_saga()
